=== pjominet/city-browser/data/countries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="countries" type="countriesType"/>
  <xs:complexType name="countryType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="countryCode"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="countriesType">
    <xs:sequence>
      <xs:element type="countryType" name="country" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== pjominet/city-browser/data/countries.xml
<?xml version="1.0" encoding="UTF-8" ?>
<countries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="countries.xsd">
    <country>
        <name>Afghanistan</name>
        <countryCode>AF</countryCode>
    </country>
    <country>
        <name>Egypt</name>
        <countryCode>EG</countryCode>
    </country>
    <country>
        <name>Ã…land Islands</name>
        <countryCode>AX</countryCode>
    </country>
    <country>
        <name>Albania</name>
        <countryCode>AL</countryCode>
    </country>
    <country>
        <name>Algeria</name>
        <countryCode>DZ</countryCode>
    </country>
    <country>
        <name>American Samoa</name>
        <countryCode>AS</countryCode>
    </country>
    <country>
        <name>Virgin Islands, U.s.</name>
        <countryCode>VI</countryCode>
    </country>
    <country>
        <name>Andorra</name>
        <countryCode>AD</countryCode>
    </country>
    <country>
        <name>Angola</name>
        <countryCode>AO</countryCode>
    </country>
    <country>
        <name>Anguilla</name>
        <countryCode>AI</countryCode>
    </country>
    <country>
        <name>Antarctica</name>
        <countryCode>AQ</countryCode>
    </country>
    <country>
        <name>Antigua And Barbuda</name>
        <countryCode>AG</countryCode>
    </country>
    <country>
        <name>Equatorial Guinea</name>
        <countryCode>GQ</countryCode>
    </country>
    <country>
        <name>Argentina</name>
        <countryCode>AR</countryCode>
    </country>
    <country>
        <name>Armenia</name>
        <countryCode>AM</countryCode>
    </country>
    <country>
        <name>Aruba</name>
        <countryCode>AW</countryCode>
    </country>
    <country>
        <name>Ascension Island</name>
        <countryCode>AC</countryCode>
    </country>
    <country>
        <name>Azerbaijan</name>
        <countryCode>AZ</countryCode>
    </country>
    <country>
        <name>Ethiopia</name>
        <countryCode>ET</countryCode>
    </country>
    <country>
        <name>Australia</name>
        <countryCode>AU</countryCode>
    </country>
    <country>
        <name>Bahamas</name>
        <countryCode>BS</countryCode>
    </country>
    <country>
        <name>Bahrain</name>
        <countryCode>BH</countryCode>
    </country>
    <country>
        <name>Bangladesh</name>
        <countryCode>BD</countryCode>
    </country>
    <country>
        <name>Barbados</name>
        <countryCode>BB</countryCode>
    </country>
    <country>
        <name>Belgium</name>
        <countryCode>BE</countryCode>
    </country>
    <country>
        <name>Belize</name>
        <countryCode>BZ</countryCode>
    </country>
    <country>
        <name>Benin</name>
        <countryCode>BJ</countryCode>
    </country>
    <country>
        <name>Bermuda</name>
        <countryCode>BM</countryCode>
    </country>
    <country>
        <name>Bhutan</name>
        <countryCode>BT</countryCode>
    </country>
    <country>
        <name>Bolivia</name>
        <countryCode>BO</countryCode>
    </country>
    <country>
        <name>Bosnia And Herzegovina</name>
        <countryCode>BA</countryCode>
    </country>
    <country>
        <name>Botswana</name>
        <countryCode>BW</countryCode>
    </country>
    <country>
        <name>Bouvet Island</name>
        <countryCode>BV</countryCode>
    </country>
    <country>
        <name>Brazil</name>
        <countryCode>BR</countryCode>
    </country>
    <country>
        <name>British Virgin Islands</name>
        <countryCode>VG</countryCode>
    </country>
    <country>
        <name>British Indian Ocean Territory</name>
        <countryCode>IO</countryCode>
    </country>
    <country>
        <name>Brunei Darussalam</name>
        <countryCode>BN</countryCode>
    </country>
    <country>
        <name>Bulgaria</name>
        <countryCode>BG</countryCode>
    </country>
    <country>
        <name>Burkina Faso</name>
        <countryCode>BF</countryCode>
    </country>
    <country>
        <name>Burundi</name>
        <countryCode>BI</countryCode>
    </country>
    <country>
        <name>Chile</name>
        <countryCode>CL</countryCode>
    </country>
    <country>
        <name>China</name>
        <countryCode>CN</countryCode>
    </country>
    <country>
        <name>Cook Islands</name>
        <countryCode>CK</countryCode>
    </country>
    <country>
        <name>Costa Rica</name>
        <countryCode>CR</countryCode>
    </country>
    <country>
        <name>Denmark</name>
        <countryCode>DK</countryCode>
    </country>
    <country>
        <name>Germany</name>
        <countryCode>DE</countryCode>
    </country>
    <country>
        <name>Saint Helena</name>
        <countryCode>SH</countryCode>
    </country>
    <country>
        <name>Diego Garcia</name>
        <countryCode>DG</countryCode>
    </country>
    <country>
        <name>Dominica</name>
        <countryCode>DM</countryCode>
    </country>
    <country>
        <name>Dominican Republic</name>
        <countryCode>DO</countryCode>
    </country>
    <country>
        <name>Djibouti</name>
        <countryCode>DJ</countryCode>
    </country>
    <country>
        <name>Ecuador</name>
        <countryCode>EC</countryCode>
    </country>
    <country>
        <name>El Salvador</name>
        <countryCode>SV</countryCode>
    </country>
    <country>
        <name>Eritrea</name>
        <countryCode>ER</countryCode>
    </country>
    <country>
        <name>Estonia</name>
        <countryCode>EE</countryCode>
    </country>
    <country>
        <name>European Union</name>
        <countryCode>EU</countryCode>
    </country>
    <country>
        <name>Falkland Islands (malvinas)</name>
        <countryCode>FK</countryCode>
    </country>
    <country>
        <name>Faroe Islands</name>
        <countryCode>FO</countryCode>
    </country>
    <country>
        <name>Fiji</name>
        <countryCode>FJ</countryCode>
    </country>
    <country>
        <name>Finland</name>
        <countryCode>FI</countryCode>
    </country>
    <country>
        <name>France</name>
        <countryCode>FR</countryCode>
    </country>
    <country>
        <name>French Guiana</name>
        <countryCode>GF</countryCode>
    </country>
    <country>
        <name>French Polynesia</name>
        <countryCode>PF</countryCode>
    </country>
    <country>
        <name>French Southern Territories</name>
        <countryCode>TF</countryCode>
    </country>
    <country>
        <name>Gabon</name>
        <countryCode>GA</countryCode>
    </country>
    <country>
        <name>The Gambia</name>
        <countryCode>GM</countryCode>
    </country>
    <country>
        <name>Georgia</name>
        <countryCode>GE</countryCode>
    </country>
    <country>
        <name>Ghana</name>
        <countryCode>GH</countryCode>
    </country>
    <country>
        <name>Gibraltar</name>
        <countryCode>GI</countryCode>
    </country>
    <country>
        <name>Grenada</name>
        <countryCode>GD</countryCode>
    </country>
    <country>
        <name>Greece</name>
        <countryCode>GR</countryCode>
    </country>
    <country>
        <name>Greenland</name>
        <countryCode>GL</countryCode>
    </country>
    <country>
        <name>Guadeloupe</name>
        <countryCode>GP</countryCode>
    </country>
    <country>
        <name>Guam</name>
        <countryCode>GU</countryCode>
    </country>
    <country>
        <name>Guatemala</name>
        <countryCode>GT</countryCode>
    </country>
    <country>
        <name>Guernsey</name>
        <countryCode>GG</countryCode>
    </country>
    <country>
        <name>Guinea</name>
        <countryCode>GN</countryCode>
    </country>
    <country>
        <name>Guinea-Bissau</name>
        <countryCode>GW</countryCode>
    </country>
    <country>
        <name>Guyana</name>
        <countryCode>GY</countryCode>
    </country>
    <country>
        <name>Haiti</name>
        <countryCode>HT</countryCode>
    </country>
    <country>
        <name>Heard Island And Mcdonald Islands</name>
        <countryCode>HM</countryCode>
    </country>
    <country>
        <name>Honduras</name>
        <countryCode>HN</countryCode>
    </country>
    <country>
        <name>Hong Kong</name>
        <countryCode>HK</countryCode>
    </country>
    <country>
        <name>India</name>
        <countryCode>IN</countryCode>
    </country>
    <country>
        <name>Indonesia</name>
        <countryCode>ID</countryCode>
    </country>
    <country>
        <name>Iraq</name>
        <countryCode>IQ</countryCode>
    </country>
    <country>
        <name>Iran</name>
        <countryCode>IR</countryCode>
    </country>
    <country>
        <name>Ireland</name>
        <countryCode>IE</countryCode>
    </country>
    <country>
        <name>Iceland</name>
        <countryCode>IS</countryCode>
    </country>
    <country>
        <name>Isle Of Man</name>
        <countryCode>IM</countryCode>
    </country>
    <country>
        <name>Israel</name>
        <countryCode>IL</countryCode>
    </country>
    <country>
        <name>Italy</name>
        <countryCode>IT</countryCode>
    </country>
    <country>
        <name>Jamaica</name>
        <countryCode>JM</countryCode>
    </country>
    <country>
        <name>Japan</name>
        <countryCode>JP</countryCode>
    </country>
    <country>
        <name>Yemen</name>
        <countryCode>YE</countryCode>
    </country>
    <country>
        <name>Jersey</name>
        <countryCode>JE</countryCode>
    </country>
    <country>
        <name>Jordan</name>
        <countryCode>JO</countryCode>
    </country>
    <country>
        <name>Cayman Islands</name>
        <countryCode>KY</countryCode>
    </country>
    <country>
        <name>Cambodia</name>
        <countryCode>KH</countryCode>
    </country>
    <country>
        <name>Cameroon</name>
